// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJtS4R9yHU6BWEzBwNI92xqTP7fC4dlTg',
    appId: '1:791100641981:web:94f90974f905024b65ddd4',
    messagingSenderId: '791100641981',
    projectId: 'game-3c5fb',
    authDomain: 'game-3c5fb.firebaseapp.com',
    storageBucket: 'game-3c5fb.appspot.com',
    measurementId: 'G-GDF3B07F2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpqromsX7Bxr7K6r5pOz117C78nUx43ys',
    appId: '1:791100641981:android:f7e5ddc34af592a865ddd4',
    messagingSenderId: '791100641981',
    projectId: 'game-3c5fb',
    storageBucket: 'game-3c5fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA00V_FhRU1KEfNUfIcpg1Bn_Odfgj0NzY',
    appId: '1:791100641981:ios:9a7c0b1cc1894c6e65ddd4',
    messagingSenderId: '791100641981',
    projectId: 'game-3c5fb',
    storageBucket: 'game-3c5fb.appspot.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA00V_FhRU1KEfNUfIcpg1Bn_Odfgj0NzY',
    appId: '1:791100641981:ios:ef4ead482ee4dee865ddd4',
    messagingSenderId: '791100641981',
    projectId: 'game-3c5fb',
    storageBucket: 'game-3c5fb.appspot.com',
    iosBundleId: 'com.example.loginpage.RunnerTests',
  );
}
